# Generated by Django 6.1.1 on 2026-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='necesidad',
            field=models.TextField(default='No especificado'),
            preserve_default=False,
        ),
    ]
